# Generated by Django 5.0.6 on 2025-09-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # La table T_E_AdminText_ADT existe déjà dans la base de données
        # Cette migration marque simplement que le modèle AdminText est maintenant
        # géré par l'application 'parametres' au lieu de 'comptabilite'
    ]
