# Generated by Django 5.2.6 on 2025-09-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='fr', max_length=5, verbose_name='Langue')),
                ('key', models.CharField(max_length=100, verbose_name='Clé')),
                ('value', models.CharField(max_length=255, verbose_name='Valeur')),
                ('display_order', models.IntegerField(db_column='ADT_DisplayOrder', default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Libellé Admin',
                'verbose_name_plural': 'Libellés Admin',
                'db_table': 'T_E_AdminText_ADT',
                'ordering': ['language', 'display_order', 'key'],
                'unique_together': {('language', 'key')},
            },
        ),
    ]
