# Generated by Django 5.2.6 on 2025-09-18 17:43

import comptabilite.dynamic_labels
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerimetreConso',
            fields=[
                ('id', models.IntegerField(db_column='PEC_Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_column='PEC_Code', max_length=50, null=True, verbose_name='Code')),
                ('libelle', models.CharField(blank=True, db_column='PEC_Libelle', max_length=255, null=True, verbose_name='Libellé')),
            ],
            options={
                'verbose_name': 'Périmètre Consolidation',
                'verbose_name_plural': 'Périmètres Consolidation',
                'db_table': 'T_E_PerimetreConso_PEC',
                'ordering': ['code', 'libelle'],
                'managed': False,
            },
            bases=(comptabilite.dynamic_labels.DynamicLabelsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PerimetreConsoSociete',
            fields=[
                ('id', models.IntegerField(db_column='PECSOC_Id', primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Périmètre Consolidation - Société',
                'verbose_name_plural': 'Périmètres Consolidation - Sociétés',
                'db_table': 'T_J_PEC_SOC',
                'managed': False,
            },
            bases=(comptabilite.dynamic_labels.DynamicLabelsMixin, models.Model),
        ),
    ]
