# Generated by Django 5.2.6 on 2025-09-12 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tiers',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tiers',
            name='societe',
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='version',
            name='societe',
        ),
        migrations.AlterModelOptions(
            name='plancomptegroupe',
            options={'ordering': ['code'], 'verbose_name': 'Groupe de Plan Comptable', 'verbose_name_plural': 'Groupes de Plan Comptable'},
        ),
        migrations.AlterModelOptions(
            name='plancomptelocal',
            options={'ordering': ['compte'], 'verbose_name': 'Compte Local', 'verbose_name_plural': 'Comptes Locaux'},
        ),
        migrations.AlterModelOptions(
            name='stade',
            options={'ordering': ['intitule'], 'verbose_name': 'Stade', 'verbose_name_plural': 'Stades'},
        ),
        migrations.AlterUniqueTogether(
            name='plancomptegroupe',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='plancomptelocal',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='naturecompte',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='naturecompte',
            name='description',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='stade',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='stade',
            name='code',
        ),
        migrations.RemoveField(
            model_name='stade',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='stade',
            name='description',
        ),
        migrations.RemoveField(
            model_name='typevaleur',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='typevaleur',
            name='description',
        ),
        migrations.AddField(
            model_name='typevaleur',
            name='commentaires',
            field=models.TextField(blank=True, db_column='TYV_Commentaires', null=True, verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='naturecompte',
            name='code',
            field=models.CharField(db_column='NCT_Code', max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='naturecompte',
            name='id',
            field=models.AutoField(db_column='NCT_Id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='naturecompte',
            name='intitule',
            field=models.CharField(db_column='NCT_Intitule', max_length=255, verbose_name='Intitulé'),
        ),
        migrations.AlterField(
            model_name='plancomptegroupe',
            name='code',
            field=models.CharField(db_column='PLG_Code', max_length=20, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='plancomptegroupe',
            name='date_creation',
            field=models.DateTimeField(blank=True, db_column='PLG_DateCreation', null=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='plancomptegroupe',
            name='date_maj',
            field=models.DateTimeField(blank=True, db_column='PLG_DateMAJ', null=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='plancomptegroupe',
            name='id',
            field=models.AutoField(db_column='PLG_Id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plancomptegroupe',
            name='intitule',
            field=models.CharField(db_column='PLG_Intitule', max_length=255, verbose_name='Intitulé'),
        ),
        migrations.AlterField(
            model_name='plancomptegroupe',
            name='nature_compte',
            field=models.ForeignKey(db_column='NCT_Id', on_delete=django.db.models.deletion.CASCADE, to='comptabilite.naturecompte', verbose_name='Nature de Compte'),
        ),
        migrations.AlterField(
            model_name='plancomptelocal',
            name='compte',
            field=models.CharField(db_column='PCL_Compte', max_length=20, verbose_name='Compte'),
        ),
        migrations.AlterField(
            model_name='plancomptelocal',
            name='date_creation',
            field=models.DateTimeField(blank=True, db_column='PLG_DateCreation', null=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='plancomptelocal',
            name='date_maj',
            field=models.DateTimeField(blank=True, db_column='PLG_DateMAJ', null=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='plancomptelocal',
            name='groupe',
            field=models.ForeignKey(db_column='PLG_Id', on_delete=django.db.models.deletion.CASCADE, to='comptabilite.plancomptegroupe', verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='plancomptelocal',
            name='id',
            field=models.AutoField(db_column='PCL_Id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plancomptelocal',
            name='intitule',
            field=models.CharField(db_column='PCL_Intitule', max_length=255, verbose_name='Intitulé'),
        ),
        migrations.AlterField(
            model_name='plancomptelocal',
            name='societe',
            field=models.ForeignKey(db_column='SOC_Id', on_delete=django.db.models.deletion.CASCADE, to='comptabilite.societe', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='archive',
            field=models.BooleanField(blank=True, db_column='SOC_Archive', null=True, verbose_name='Archivé'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='code',
            field=models.CharField(db_column='SOC_Code', max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='devise_id',
            field=models.IntegerField(blank=True, db_column='DEV_Id', null=True, verbose_name='ID Devise'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='groupe',
            field=models.BooleanField(db_column='SOC_Groupe', default=False, verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='id',
            field=models.AutoField(db_column='SOC_Id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='societe',
            name='intitule',
            field=models.CharField(db_column='SOC_Intitule', max_length=255, verbose_name='Intitulé'),
        ),
        migrations.AlterField(
            model_name='stade',
            name='id',
            field=models.AutoField(db_column='STA_Id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stade',
            name='intitule',
            field=models.CharField(db_column='STA_Intitule', max_length=255, verbose_name='Intitulé'),
        ),
        migrations.AlterField(
            model_name='typevaleur',
            name='code',
            field=models.CharField(db_column='TYV_code', max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typevaleur',
            name='id',
            field=models.AutoField(db_column='TYV_Id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typevaleur',
            name='intitule',
            field=models.CharField(db_column='TYV_Intitule', max_length=255, verbose_name='Intitulé'),
        ),
        migrations.DeleteModel(
            name='FinanceFaits',
        ),
        migrations.DeleteModel(
            name='Tiers',
        ),
        migrations.DeleteModel(
            name='Version',
        ),
        migrations.RemoveField(
            model_name='plancomptegroupe',
            name='societe',
        ),
    ]
