# Generated by Django 5.2.6 on 2025-09-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_alter_tiers_unique_together_remove_tiers_societe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturecompte',
            name='id',
            field=models.IntegerField(db_column='NCT_Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='id',
            field=models.IntegerField(db_column='SOC_Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stade',
            name='id',
            field=models.IntegerField(db_column='STA_Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='typevaleur',
            name='id',
            field=models.IntegerField(db_column='TYV_Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
