# Generated by Django 5.0.6 on 2025-09-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0003_alter_naturecompte_id_alter_societe_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='fr', max_length=5, verbose_name='Langue')),
                ('key', models.CharField(max_length=100, verbose_name='Clé')),
                ('value', models.CharField(max_length=255, verbose_name='Valeur')),
            ],
            options={
                'verbose_name': 'Libellé Admin',
                'verbose_name_plural': 'Libellés Admin',
                'db_table': 'T_E_AdminText_ADT',
                'ordering': ['language', 'key'],
                'unique_together': {('language', 'key')},
            },
        ),
    ]
