# Generated by Django 5.0.6 on 2025-09-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0004_devise_admintext'),
    ]

    operations = [
        # Migration factice - la colonne DEV_Id et la contrainte FK existent déjà
        # dans la base de données. Cette migration marque simplement que le champ
        # devise a été ajouté au modèle Django.
    ]