# Generated by Django 5.0.6 on 2025-09-15 20:52

import comptabilite.dynamic_labels
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0005_add_devise_foreignkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.IntegerField(db_column='DEV_Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('code_iso', models.CharField(blank=True, db_column='DEV_CodeIso', max_length=3, null=True, verbose_name='Code ISO')),
                ('intitule', models.CharField(blank=True, db_column='DEV_Intitule', max_length=20, null=True, verbose_name='Intitulé')),
                ('sigle', models.CharField(blank=True, db_column='DEV_Sigle', max_length=3, null=True, verbose_name='Sigle')),
            ],
            options={
                'verbose_name': 'Devise',
                'verbose_name_plural': 'Devises',
                'db_table': 'T_E_Devises_DEV',
                'ordering': ['code_iso'],
            },
            bases=(comptabilite.dynamic_labels.DynamicLabelsMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='AdminText',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='devise_id',
        ),
        migrations.AddField(
            model_name='societe',
            name='devise',
            field=models.ForeignKey(blank=True, db_column='DEV_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.devise', verbose_name='Devise'),
        ),
    ]
